### ISSUE TITLE
Cuda version

### ISSUE THREAD

**Issue by Bongnah** [cynricfu/MAGNN#45]

**Comment by Bongnah** [comment]
Traceback (most recent call last):
  File "run_DBLP.py", line 204, in <module>
    args.epoch, args.patience, args.batch_size, args.samples, args.repeat, args.save_postfix)
  File "run_DBLP.py", line 93, in run_model_DBLP
    (train_g_list, features_list, type_mask, train_indices_list, train_idx_batch_mapped_list))
  File "/Desktop/miniconda3/envs/MAGNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Desktop/model/MAGNN_nc_mb.py", line 113, in forward
    transformed_features[node_indices] = fc(features_list[i])
  File "/Desktop/miniconda3/envs/MAGNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Desktop/miniconda3/envs/MAGNN/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/Desktop/miniconda3/envs/MAGNN/lib/python3.6/site-packages/torch/nn/functional.py", line 1369, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Because I always get this error.
